### ISSUE TITLE
No module named pcapy

### ISSUE THREAD

**Issue by XpliSyL** [medbenali/CyberScan#1]
I got this error everytime I try to launch the script :(
I'm running macOS Sierra version 10.12.6, python 2.7.13
```
 python CyberScan.py 
Traceback (most recent call last):
  File "CyberScan.py", line 27, in <module>
    from scapy.all import *
  File "/Users/0x73764c/CyberScan/scapy/all.py", line 16, in <module>
    from arch import *
  File "/Users/0x73764c/CyberScan/scapy/arch/__init__.py", line 75, in <module>
    from bsd import *
  File "/Users/0x73764c/CyberScan/scapy/arch/bsd.py", line 12, in <module>
    from unix import *
  File "/Users/0x73764c/CyberScan/scapy/arch/unix.py", line 20, in <module>
    from pcapdnet import *
  File "/Users/0x73764c/CyberScan/scapy/arch/pcapdnet.py", line 30, in <module>
    import pcapy as pcap
ImportError: No module named pcapy
```

> CyberScan works out of the box with Python version 2.6.x and 2.7.x.

Well I guess not :(

**Comment by medbenali** [comment]
hello , the bug is fixed , thanks
