### ISSUE TITLE
ImportError: No module named pcapy

### ISSUE THREAD

**Issue by Wykz** [medbenali/CyberScan#6]
I got this error everytime I try to launch the script :(
I'm running Windows 10, python 2.7.13

`$ python CyberScan.py
Traceback (most recent call last):
  File "CyberScan.py", line 28, in <module>
    from scapy.all import *
  File "C:\Users\clore\Desktop\CyberScan-1.1.1\scapy\all.py", line 16, in <module>
    from arch import *
  File "C:\Users\clore\Desktop\CyberScan-1.1.1\scapy\arch\__init__.py", line 79, in <module>
    from windows import *
  File "C:\Users\clore\Desktop\CyberScan-1.1.1\scapy\arch\windows\__init__.py", line 23, in <module>
    from scapy.arch import pcapdnet
  File "C:\Users\clore\Desktop\CyberScan-1.1.1\scapy\arch\pcapdnet.py", line 30, in <module>
    import pcapy as pcap
ImportError: No module named pcapy
`

**Comment by D3m0ni4k** [comment]
pip install pcapy

**Comment by tomovic** [comment]
I have Python 2.7
I install VS 2010

C:\sulley_build>c:\Python27\Scripts\pip install pcapy==0.11.2
Downloading/unpacking pcapy==0.11.2
Downloading pcapy-0.11.2.tar.gz
Running setup.py (path:c:\users\tomycat\appdata\local\temp\pip_build_tomycat\p
capy\setup.py) egg_info for package pcapy

Installing collected packages: pcapy
Running setup.py install for pcapy
building 'pcapy' extension
error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat).
Get it from http://aka.ms/vcpython27
Complete output from command C:\Python27\python.exe -c "import setuptools, t
okenize;__file__='c:\\users\\tomycat\\appdata\\local\\temp\\pip_build_tomycat\\p
capy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().re
place('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\tomycat\appda
ta\local\temp\pip-4smeiu-record\install-record.txt --single-version-externally-m
anaged --compile:
running install

running build

running build_ext

building 'pcapy' extension

error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get
it from http://aka.ms/vcpython27

----------------------------------------
Cleaning up...
Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\use
rs\\tomycat\\appdata\\local\\temp\\pip_build_tomycat\\pcapy\\setup.py';exec(comp
ile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __fi
le__, 'exec'))" install --record c:\users\tomycat\appdata\local\temp\pip-4smeiu-
record\install-record.txt --single-version-externally-managed --compile failed w
ith error code 1 in c:\users\tomycat\appdata\local\temp\pip_build_tomycat\pcapy
Storing debug log for failure in C:\Users\tomycat\pip\pip.log

C:\sulley_build>
